### ISSUE TITLE
Alloy Smelter and Metal Press voids the energy

### ISSUE THREAD

**Issue by LopyLuna** [KhanhPham05/ToTheMoon#10]
**Alloy Smelter and Metal Press voids the energy**
![2022-04-26_16 47 49](https://user-images.githubusercontent.com/100169742/165416285-87c9a458-4a0e-43b8-821a-d2599ee2f587.png)
![2022-04-26_16 47 54](https://user-images.githubusercontent.com/100169742/165416275-aa1bc246-0409-4304-b7ae-881b50611e5f.png)

**Comment by KhanhPham05** [comment]
the GUI is bugged in this build, i have fixed it in dev
