### ISSUE TITLE
Possibly a Visual Bug or voids energy after the energy storage is full of energy

### ISSUE THREAD

**Issue by LopyLuna** [KhanhPham05/ToTheMoon#16]
**Possibly a Visual Bug or voids energy after the energy storage is full of energy**
![2022-04-27_07 25 09](https://user-images.githubusercontent.com/100169742/165555785-e9aacb10-abe1-4691-8ccc-0a982bf420b0.png)

**Comment by KhanhPham05** [comment]
This maybe because the block that still consumes the energy even it was full
