### ISSUE TITLE
Create Mod with the machines corrupts the world

### ISSUE THREAD

**Issue by LopyLuna** [KhanhPham05/ToTheMoon#25]
**Create Mod with the machines corrupts the world**
as I know so far the funnel, chute, anything that extract items from the machines in the mod corrupts the world

**Comment by KhanhPham05** [comment]
can you please provide the crash report ?

**Comment by LopyLuna** [comment]
> **can you please provide the crash report ?**
here is the crash report
[crash-2022-05-01_04.29.41-server.txt](https://github.com/KhanhPham05/ToTheMoon/files/8598995/crash-2022-05-01_04.29.41-server.txt)
