### ISSUE TITLE
Crash caused by tothemoonRegistry Object not present: tothemoon:copper_machine_frame

### ISSUE THREAD

**Issue by Thepigcat76** [KhanhPham05/ToTheMoon#43]
My game crashed and the crash report says that: Registry Object not present: tothemoon:copper_machine_frame

**Comment by KhanhPham05** [comment]
Okay so can you tell me the mod version please ?

**Comment by Thepigcat76** [comment]
it crashed when using 0.3.0

**Comment by KhanhPham05** [comment]
> it crashed when using 0.3.0

So the forge version is 73 right, i mean the last 2 digit

**Comment by Thepigcat76** [comment]
well this is the crash report 
[crash-2022-08-28_13.52.11-client.txt](https://github.com/KhanhPham05/ToTheMoon/files/9439596/crash-2022-08-28_13.52.11-client.txt)
and im using forge version 74

**Comment by KhanhPham05** [comment]
Would you mind running the game with the mod itself, and no other extra mods? I can not reproduce the issue on my end with the exact versions that you gave to me

**Comment by Thepigcat76** [comment]
I have just done that and im now looking for another mod that might have caused it

**Comment by KhanhPham05** [comment]
It is caused from Block#appendHoverText

**Comment by KhanhPham05** [comment]
Okay, I found it, it is an incompatibility issue with Supplementaries

**Comment by KhanhPham05** [comment]
@taraxsmallboy Well, you haven't installed the required library mod for Suppliementary.
[Moonlight Lib](https://www.curseforge.com/minecraft/mc-mods/selene/files/3842421)
