### ISSUE TITLE
Suggestion: Add item acceptor for the Blackstone furnace

### ISSUE THREAD

**Issue by Thepigcat76** [KhanhPham05/ToTheMoon#47]
Currently there is no good way to automate inputs/outputs thats why it would be very good if there was an item acceptor like the fluid acceptor.

**Comment by KhanhPham05** [comment]
> Currently there is no good way to automate inputs/outputs thats why it would be very good if there was an item acceptor like the fluid acceptor.

1.20.1 version is now implemented item acceptor for the multiblock.
